### ISSUE TITLE
Configurable keys

### ISSUE THREAD

**Issue by Calinou** [KOBUGE-Games/ringed#1]
The ability to change the keys used to move and shoot would be appreciated.

**Comment by ObaniGemini** [comment]
Player can now move with arrows
*bojidar-bg

**Comment by ObaniGemini** [comment]
Maybe that menu that @akien-mga made for dynadungeons would be useful ?

**Comment by erik90mx** [comment]
I was thinking in the same thing @ObaniGemini  , I will see that code for sure :)

**Comment by mamarilmanson** [comment]
It really seems Ringed will need its own website soon… :D

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ well, maybe :smile:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ will try hard to start studying wordpress... :D

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ Well, WP is simple, selecting the hosting service is harder :smile: (tuxfamily is an option...)

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ but at this moment I'm 0 at wordpress... -____-

It might also jumpstart my webdesign career... :)

**Comment by alketii** [comment]
Hosting is provided in our main website http://kobuge.org/reines

**Comment by mamarilmanson** [comment]
@alketii ~ says page not found...

**Comment by erik90mx** [comment]
I added the menu and actually it works, but I need to make the config persistent when close and reopen.
https://github.com/KOBUGE-Games/ringed/commit/dc87089d7b10c9ab3727d154ce5c53b16cbf5dbe

**Comment by erik90mx** [comment]
Now the config is persistent https://github.com/KOBUGE-Games/ringed/commit/6e4ca6ddf6e91382017042b91e6d53191c6b151c

We need to know what are all the possible actions that the player will do.

**Comment by bojidar-bg** [comment]
@alketii I think you mean http://kobuge.org/ringed, right?

**Comment by Etiell** [comment]
Hello :D

**Comment by bojidar-bg** [comment]
@Etiell Hi :D
