### ISSUE TITLE
Day and Night mechanics

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#10]
Well like was mentioned in the chat, there is a change to implement day and night mechanics in the game (maybe the enemies are resources or are friendly in the day... etc.)

**Comment by bojidar-bg** [comment]
Well, maybe not friendly, but less aggressive at least.

**Comment by erik90mx** [comment]
I'm thinking in put a clock in the HUD and the days the player "survive" just to feel like a spartan :)
