### ISSUE TITLE
[Feature Request] Trees

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#14]
![screen shot 2015-06-15 at 10 40 45 pm](https://cloud.githubusercontent.com/assets/3820189/8162420/a4404d7e-13af-11e5-81ae-4c9bdae6fccf.png)

Add trees with this concept… they have a collisionshape2D with radius greater than the sprite that when triggered will make the leaves ONLY transparent(but not completely)… :)

**Comment by bojidar-bg** [comment]
Ok, to explain in 'godot' terms:
- The tree has an Area2D child (larger than the sprite itself), that will make the leaves transparent, should the player go underneath. (notes for implemetation - make it 3x the size of the sprite, and interpolate opacity based on distance)
- Then, the real collider of that staticBody2D tree node will cover just the trunk.

@mamarilmanson your idea with the transparent leaves isn't bad...

**Comment by mamarilmanson** [comment]
yes indeed... if you could implement this using placeholders then I can replace them with art that I will make... :)
