### ISSUE TITLE
Bombs enhancement

### ISSUE THREAD

**Issue by bojidar-bg** [KOBUGE-Games/ringed#16]
The bombs will look (and sound) better if they emit sound and light on explode. (for implementation look at the bomb.xml::AnimationPlayer node, and add some keyframes for the light, the sound is pretty straightforward I guess)

**Comment by erik90mx** [comment]
Now it has a light animation when it explodes and a sound, in this commit: https://github.com/KOBUGE-Games/ringed/commit/7ac535e749fc3e3a0194ee44af3ec1a114500341
