### ISSUE TITLE
[Bug] Light Issue

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#17]
I  don't know what happened but the light in the game became like this???
![light_issue](https://cloud.githubusercontent.com/assets/3820189/8174421/fca7af3e-140e-11e5-925e-6ae6937e7c5f.png)

**Comment by erik90mx** [comment]
Well I just tested that Canvas Modulate param, to make the spiders more difficult to see when you are with low life = low light , to achieve a king "fog of war" and don't see the enemy approaching so easy.

But we can discuss a better approach for that @bojidar-bg  @mamarilmanson @akien-mga

**Comment by bojidar-bg** [comment]
I think it will look better it we can blur the shadows a bit... I will check tonight if this is possible with shaders :smile:
