### ISSUE TITLE
New Game Icon... 

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#20]
https://github.com/mamarilmanson/ringed/commit/c4c3aa7812d4906d10fe18545999450cef6511be

This is still a commit to my fork... some conflicts are present because I also pushed other commits to mine... please review... :)

**Comment by bojidar-bg** [comment]
The icon is way to huge... 1000x1000 is not a very good idea :smile: Better decrease it to something like 128x128 or 512x512.

Also, I don't personally think that the game will be all about killing spiders //o\, so maybe showcase something else on the icon?

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ what do you mean it will not be about killing spiders??? :)

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ I mean that there will be some other primary goal and plot driver, and that the spiders will be just to scare off noobs :ghost:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ that was... so... sad... I was actually on the stage to put this as a menu screen... :D

https://github.com/mamarilmanson/ringed/blob/master/gfx/cover_art.png

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ Ok, maybe have a couple of game modes like "spider genocide", "long-term survival", "creative", etc. ? :smile:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ sorry I'm confused... what do you mean have game modes?

**Comment by bojidar-bg** [comment]
(This comment is getting a bit off-topic....)
@mamarilmanson ~ like different logics for some main class.
- the spider genocide mode will be just like now.
- the 'long-term' survival will be mainly concerned about collecting resources (wood, stone, wheat, and the like).
- the creative mode will be just like survival, but you will have all the resources in infinite amounts.

OFC, all those modes will have a multiplayer version available too.

(if you are still confused, you will have to wait about an hour and a half before I'm on IRC)

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ you're still talking about arts? right? :)

**Comment by erik90mx** [comment]
@bojidar-bg  I was thinking in make an icon to found the game faster in Godot (a placeholder for now)

**Comment by erik90mx** [comment]
@bojidar-bg and @mamarilmanson  if we will conserve the current icon, I will close this issue, it is Ok?

**Comment by bojidar-bg** [comment]
@erik90mx No problem :smile:

**Comment by mamarilmanson** [comment]
:+1:
