### ISSUE TITLE
Kamikaze Spider

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#22]
Well like the title said, I was thinking in made a kamikaze spider (maybe fast, with red stomach with a big light in it, low life, and bad attitude) to scare the player and make him be more aware of the night beasts >:)

**Comment by bojidar-bg** [comment]
@erik90mx stop thinking of spiders, think of some other insect/animal :P

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ may I ask why? :)

**Comment by erik90mx** [comment]
@bojidar-bg yep is a good idea think in spiders, maybe they are the first noob targets :) we can improve them latter of change the art (but we need proposals)

**Comment by erik90mx** [comment]
I added that spiders with this commit https://github.com/KOBUGE-Games/ringed/commit/b97e91189da9246ebc4358f3c8015e95c9755db0
