### ISSUE TITLE
Add dodge action with spacebar

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#26]
Well when I'm playing I just imagine that the player can make a dodge to miss an enemy attack (to add more combat options and ability to the game)

**Comment by bojidar-bg** [comment]
+2

**Comment by ObaniGemini** [comment]
Maybe dodge should have frames of invulnerability ? Cause actually it's not very useful :)

**Comment by erik90mx** [comment]
maybe more dodge distance instead of invulnerability? I like that things get difficult sometime

**Comment by bojidar-bg** [comment]
@erik90mx yeah, more distance, no invulnerability.... :+1:

**Comment by bojidar-bg** [comment]
Will fix tonight (if I delete TeeWorlds first :smile: )

**Comment by ObaniGemini** [comment]
Could dodge action be activated by double clicking on an arrow key, instead of spacebar?

**Comment by bojidar-bg** [comment]
@ObaniGemini double-tap will
1. ignore mouse position (so you will be forced to dodge in one of the cardinal directions)
2. be most likely used to trigger running instead...

**Comment by bojidar-bg** [comment]
from https://github.com/KOBUGE-Games/ringed/commit/d43b38788428d8ab46b12d32d0f559ab8e3f1be6#commitcomment-11818066 :
@erik90mx ~ Can you please add some more exported variables, so they will show up in the inspector?
Also, you should rename the action from "spacebar" to "dodge"
Plus, dodge should move the player, and not just be another form of running

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ what do you mean direction of the mouse??? :)

What I think is that if I point the mouse to the enemy I will dodge "towards" the spiders???

**Comment by ObaniGemini** [comment]
@bojidar-bg : arrows already make move in cardinal directions -.-

**Comment by bojidar-bg** [comment]
@mamarilmanson  hope you won't press dodge while you are still pointing at them... and BTW, you are running away from them, not shooting them...

But, anyway... we can then have consensus if we say that space dashes in direction of the mouse, and double-arrows – in cardinal directions... fine? :smile:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ the words are too deep... O_O

**Comment by ObaniGemini** [comment]
@bojidar-bg lol ok :p

**Comment by erik90mx** [comment]
I added the double key press to dodge, in this commit:  https://github.com/KOBUGE-Games/ringed/commit/3dbb4f5590b4a31ac5778d2d486cc99a224670a6

the only thing that I noticed is that it doesn't dodge in diagonal now @bojidar-bg 
about move the player for dodge, how is made that?
