### ISSUE TITLE
Add multiplayer needed menus

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#28]
Well in order to get multiplayer ready to dev in Ringed we need to prepare first the menus to Host a game and Join to one (we can copy some Reines nodes to make it work)

Then @est31 will try to make the multiplayer feature, when this is ready :)

**Comment by mamarilmanson** [comment]
Proposal for menu list:

Single Player
Multiplayer
[sub]Home (or something like this...)
[sub]Visitor (or something like this...)
Options
Exit

**Comment by ObaniGemini** [comment]
Maybe add a "Help" menu after the options menu? :)

**Comment by bojidar-bg** [comment]
@mamarilmanson What about opening separate issues for the other menus? :smile: (I think we have them already..)
