### ISSUE TITLE
Light bug when reloads the scene

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#29]
Well when the game is executed first, it will look good when you fire the gun
http://i.imgur.com/CCXxOki.png

Sometimes when you die and the scene needs to be reloaded this kind of things happend:
http://i.imgur.com/s9UGuxh.png

(The back Light2D with type don't appears)

or this

http://i.imgur.com/g3Blzul.png
(the shotLight isn't appearing)

In case both 

_I just notice that, when you died but still fire, the reload scene now works normally (whit the Light2D with sub type and the ShotLight)_

**Comment by erik90mx** [comment]
I was thinking in avoid that kind of issues with light nodes, changing the material of the spiders to normal (right now they just can be seen by a light of kind MIX) and this issue is causing that when the light energy is reduced (when an enemy hit you) and is  a clear day (not night) the light seems dark (because it is kind MIX)

**Comment by bojidar-bg** [comment]
@erik90mx what about changing it to "add" ?

**Comment by erik90mx** [comment]
@bojidar-bg the spiders looks like alpha and glow, I try that before the MIX mode, so I need to disable the shader of the spiders to be a normal one and the lights to be in ADD mode, so now we can see them approaching to us (and the idea of the actual spider shader is that we can make them invisible when the light is not touching them)

**Comment by bojidar-bg** [comment]
@erik90mx ~ I see... :smile: Maybe we should gradually decrease the player's light as the day starts? And about the spiders.... I think that a custom shader might do the job...

**Comment by erik90mx** [comment]
this commit seems like fix it:
https://github.com/KOBUGE-Games/ringed/commit/813b7068192595c8f30100abf9ff1adf467e159e

now the lights need to be off the the night comes

**Comment by mamarilmanson** [comment]
was this revised not to reload everything to accommodate multiplayer?

**Comment by erik90mx** [comment]
@mamarilmanson  yea but, in order to resolve some of these things: https://github.com/KOBUGE-Games/ringed/issues/35

It fixed this issue too
