### ISSUE TITLE
Make the multiplayer server 

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#30]
After a death match between @bojidar-bg  and @est31 

We decide that @est31 will make the server based in this class (Reines game)
https://github.com/KOBUGE-Games/reines/blob/master/server.gd

may the multiplayer games begin!

**Comment by mamarilmanson** [comment]
:+1:

**Comment by bojidar-bg** [comment]
#19 needs to get resolved first.

**Comment by est31** [comment]
Dupe of #11
