### ISSUE TITLE
Spawner Art

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#32]
Spawner art to add to the map sent to Kobuge Mailing List...

**Comment by bojidar-bg** [comment]
How to get it out of there? :smile:

**Comment by mamarilmanson** [comment]
download the zip file... it's on png format... :D

**Comment by bojidar-bg** [comment]
Can you send it again, because we hadn't set the archiving up back then...

**Comment by mamarilmanson** [comment]
@ObaniGemini ~ what do you mean Medias@Graphics?

**Comment by bojidar-bg** [comment]
That's already fixed
