### ISSUE TITLE
Slow motion bullets when you run against its direction 

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#34]
If you fire to the right and run to the left, you will see slow motion bullets (is a nice effect btw)

_The slow motion bullets are like mines if the spiders touch them, and you will feel like Neo if you touch them with the player_

**Comment by bojidar-bg** [comment]
This happens because the bullet takes the player's velocity when it is shot.

**Comment by bojidar-bg** [comment]
Can be fixed easily if the player velocity is divided by some amount here https://github.com/KOBUGE-Games/ringed/blob/master/scripts/gun.gd#L44 . (best if it is an exported var of the bullet script (should also be done in bomb.gd))

**Comment by bojidar-bg** [comment]
@ObaniGemini what should the To resolve tag mean?

**Comment by ObaniGemini** [comment]
That it's a problem To resolve @bojidar-bg :)

**Comment by bojidar-bg** [comment]
@erik90mx if you haven't fixed it tonight, I'll fix it instead :smile:

**Comment by erik90mx** [comment]
fixed with this commit
https://github.com/KOBUGE-Games/ringed/commit/80a091b57093bf0e2fc1d4d179997e2351082e9a
