### ISSUE TITLE
Some Reports about Enhancement and Proposals after testing the latest commit... 

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#35]
- Spider only appearing when coming closer even on daytime...
- Flashlight is on even on a day period...
- Propose to add a pause window when player pressed ESC...
- Add number of kills...

@bojidar-bg ~ I think we really need to finish the game level... -____-

**Comment by ObaniGemini** [comment]
Maybe their could be also some objectives to win level, as surviver "X" Days or kill "X" ennemies.

**Comment by bojidar-bg** [comment]
@ObaniGemini this will change the game from a sandbox game into a adventure game... In a sandbox game you would win levels be earning exp. In an adventure game, you would win levels by just "doing that quest for level X".

@ObaniGemini BTW, can you open an issue in which we will choose the exact style of the game (is it RPG, sandbox, adventure, card-trading, or whatever else...) :smile: 

And yeah, if you want to just promote the "objective = exp/level" idea, better open a new issue.....

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ how about L4D as a reference for gameplay? somehow... :)

But we still need to think of a concrete gameplay first based if we are going to concentrate on Single Player of Multi Player...

**Comment by erik90mx** [comment]
Well something hit my head: what about a simple game mechanic for now, of two teams (users) and the winner is the one that destroy all the colored boxes of the other one (they have to cross the spiders and monsters to do the job), but obviously the other team can protect their precious boxes and make a great war.

We can implement some mechanics based in this simple concept, ej: you kill a number of spiders you can get money/points to make a box or something to diversify the gameplay and player behavior.

**Comment by ObaniGemini** [comment]
Also, maybe should there be weapons on the floor at some places that player could take. As it, at the beginning, he would only have a pistol and would have to search to find the machinegun and the grenade launcher.

**Comment by bojidar-bg** [comment]
@ObaniGemini #4 ?

**Comment by ObaniGemini** [comment]
@bojidar-bg Yes, forgot it ^^

**Comment by bojidar-bg** [comment]
@KOBUGE-Games/owners Please open new issues for new suggestions, because most comments are quite [O]ff-[T]opic...

Also, you can delete comments if you want..

**Comment by erik90mx** [comment]
Done :)
