### ISSUE TITLE
Melee weapon and defence

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#37]
Well I was thinking in a kind of defence to reduce damage is is pressed at the right time, and a melee weapon to make more damage or backstabbing.

**Comment by bojidar-bg** [comment]
We can bind RMB (right mouse button) to a shield of some kind (check http://www.treasurearena.com/ for "inspiration")

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ then we might need to change the "change weapon" to character 'E' ...

**Comment by bojidar-bg** [comment]
@mamarilmanson do you have a MMB (middle mouse button) or at least a scroll wheel? :mouse:

**Comment by mamarilmanson** [comment]
yes... oohhh... ok... I get the idea... :D

**Comment by erik90mx** [comment]
@bojidar-bg  can you help me with this issue?

**Comment by bojidar-bg** [comment]
@erik90mx ~ Maybe Monday night... (e.g. Morning for you..) cus I'm a bit busy this weekend?

**Comment by erik90mx** [comment]
@bojidar-bg ok that's ok  :)

**Comment by bojidar-bg** [comment]
@erik90mx Opss.. sorry.. I was too busy... Maybe I'll try this week, but... who know if I'll be able to do it :smile:

**Comment by erik90mx** [comment]
@bojidar-bg  When I finish to work directly with Yoli in the stories, I will focus more in the dev of the milestones issues, so if I finish mine I will assign the issue to myself if is Ok at that moment.

**Comment by bojidar-bg** [comment]
Ok, in cb4ab2373c978e88a4571a582eec66d451d11a69 I added the sword, needs some more tweaking though.

**Comment by erik90mx** [comment]
@bojidar-bg  I make some changes in this commit:  https://github.com/KOBUGE-Games/ringed/commit/666a0b496140dbce666f221c8be37141ca82ba01

**Comment by erik90mx** [comment]
I added the shield in this commit:  https://github.com/KOBUGE-Games/ringed/commit/6279be3dd9ad77b24e7d9e75915d4ce51eada2c6
