### ISSUE TITLE
Better GUI in Fullscreen mode

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#40]
Well we have now Fullscreen mode in the Graphics options
https://github.com/KOBUGE-Games/ringed/commit/a89fa5f48d9c63e87fc814e3bc95a20e85699107

now we need to adjust the menu's GUI to adapt smoothly.

**Comment by bojidar-bg** [comment]
The main problem is that the menu script is not made to update those menus see how I've made the join and host sub-menus - https://github.com/KOBUGE-Games/ringed/blob/master/scripts/menu.gd#L63 . :smile:

**Comment by bojidar-bg** [comment]
ping?

**Comment by erik90mx** [comment]
@bojidar-bg  I was working with Yoli in the stories proposals :)

**Comment by bojidar-bg** [comment]
ops, forgot it :smile:

**Comment by bojidar-bg** [comment]
Will push a nice fix very soon :smiley:

**Comment by bojidar-bg** [comment]
Closed in a311860d739cd14322c6d4610d34edabbc0e845f and c41c69892ed2a05c2ebf9e331c79e212317243e4
