### ISSUE TITLE
Make health and stamina regenerate smoothly

### ISSUE THREAD

**Issue by Calinou** [KOBUGE-Games/ringed#41]
Currently, they don't regenerate smoothly.

**Comment by erik90mx** [comment]
@Calinou well I think we can do the same that in this issue
https://github.com/KOBUGE-Games/ringed/issues/42
The stamina regenerates smooth because its cooldown is little and its amount too = fast regeneration but in tiny steps that give us the sensation of smoothness

**Comment by bojidar-bg** [comment]
@erik90mx You might consider using Tween-s to make it animate.

**Comment by erik90mx** [comment]
@bojidar-bg  well I think it depends on what it is "smoothly" 
- The bars increments slow (like the health right now) and in normal steps of 1.0, but with a tween
- Or the bars recover seems constant

the damange will be slow too? @Calinou

**Comment by erik90mx** [comment]
Well after read the Tween documentation (it need love), now I implement it in the update methods of the stamina and heatlh, in this commit: https://github.com/KOBUGE-Games/ringed/commit/a30225cc509331a25718e6e421c88b1de0f42785
