### ISSUE TITLE
Show level titles in the menu instead of filenames

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#43]
@erik90mx or @bojidar-bg: If possible I suggest (something like) this...

From: res://maps/forest_1.xml

To: Forest 1

:+1: ?

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ so... what do you mean? (can't understand, maybe post some more info)

**Comment by bojidar-bg** [comment]
You mean that we should show a title (like "Forest 1") instead of the path?

**Comment by Calinou** [comment]
> You mean that we should show a title (like "Forest 1") instead of the path?

Yes, exactly.

Additionally, we might show a more complete description (plus a short backstory).

**Comment by ObaniGemini** [comment]
And a screenshot, maybe?

**Comment by mamarilmanson** [comment]
@ObaniGemini ~ screenshot??? If I don't have office tomorrow I'll study about it... :D

**Comment by ObaniGemini** [comment]
256x256 picture :)

**Comment by mamarilmanson** [comment]
@ObaniGemini ~ what I mean is a screenshot about what??? 

XD

**Comment by erik90mx** [comment]
@mamarilmanson they are talking about make that menu with a map screenshot, that way the player can choose seeing the image of what he choose.

**Comment by ObaniGemini** [comment]
Thanks for the better explanation @erik90mx :)
This is used in many games and mostly action games/FPSs

**Comment by bojidar-bg** [comment]
:+1: Nice idea!

**Comment by mamarilmanson** [comment]
ah! maybe you mean the thumbnail... :D

**Comment by bojidar-bg** [comment]
I'll start to work on this.

**Comment by bojidar-bg** [comment]
Ok, partly done: 04795f39195e9e21ce4b32f9fb260778a2ed7a43

No thumbnails yet. @erik90mx  Do you think you can add them easily?

**Comment by erik90mx** [comment]
@bojidar-bg well depends, it will be generated dynamically?

**Comment by bojidar-bg** [comment]
@erik90mx OFC not! It will be just a png image :laughing:

**Comment by erik90mx** [comment]
@bojidar-bg  ok sounds easy, I will do it :)

**Comment by erik90mx** [comment]
Added the previews in this commit: https://github.com/KOBUGE-Games/ringed/commit/cc2d2666706f059dad3b059882e83b125e6f40c1
