### ISSUE TITLE
Kobuge Identity

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#44]
I tried to turn the logo from pencil to pixel... have a look... please enjoy... :)

*I also sent this on the mailing list... 
![kobuge_games_logo](https://cloud.githubusercontent.com/assets/3820189/8468122/8254b5f4-209a-11e5-98ef-eb247e9706b6.png)

**Comment by bojidar-bg** [comment]
Can you make the thinest part of the K a bit wider (the K in the logo, not the one in the text) ? I think it will look better then :smile: .

**Comment by mamarilmanson** [comment]
ok... revision 1! :D

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ BTW, you are making it in some vector program (e.g. Inkscape), right? :smile_cat:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ yes... why do you ask? :)

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ I want to be sure that I won't need to convert it after it is a complete (bitmap) image *wink*

**Comment by mamarilmanson** [comment]
oh... ok... :)

**Comment by mamarilmanson** [comment]
![kobuge_games_logo](https://cloud.githubusercontent.com/assets/3820189/8472139/3aa4034a-20d1-11e5-9133-3790af4a09e6.jpg)

**Comment by bojidar-bg** [comment]
:+1: for the "3D" version :smile: 
The flat version doesn't look flat... somehow?! Maybe you can make the flat `K` of only 5 segments (instead of the current 7 segments)?
@mamarilmanson "Keep up the good work" ;)

**Comment by ObaniGemini** [comment]
Wow...NICE !!!!!

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ I don't quite understand about the segments... can you explain further? XD

btw... to anyone who maybe concerned??? on a weekend where everyone maybe awake I'd like to ask about gui in godot... I'm planning to do something regarding Ringed menus... :D

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ I mean to make the flat K using only 5 lines, not 7 lines. (yes, that means that it will be a concave pentagon)

BTW, to anybody that might be interested, during the weekend I **_might**_ find some time to explain the way one can theme GUI's in godot :smile: ( @mamarilmanson you meant that, right? )

**Comment by mamarilmanson** [comment]
specifically I want to program GUI for user interaction... not only the frontend but also the backend of it... :)

**Comment by erik90mx** [comment]
I like it and the idea of better GUI design sounds great >:)

**Comment by ObaniGemini** [comment]
For now I'm working more on some other project so the only thing I can do for you is musics, and sounds (maybe), bue not with a great productivity.

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ I'll edit this and send this (when time allows) on the mailing list... :)

**Comment by mamarilmanson** [comment]
And another off-topic: http://blogs.unity3d.com/2015/07/01/the-state-of-unity-on-linux/

**Comment by mamarilmanson** [comment]
another, go click more on the green thumbnails: https://www.youtube.com/user/ExtraCreditz

:D

**Comment by erik90mx** [comment]
@mamarilmanson  I saw the link before in the chat, it is better to share this kind of material in the mail list :)

**Comment by mamarilmanson** [comment]
will do... :+1:

**Comment by mamarilmanson** [comment]
![kobuge_games_logo](https://cloud.githubusercontent.com/assets/3820189/8515504/6c0c1e1a-23d6-11e5-9ff3-3d614d2af8dd.jpg)

**Comment by bojidar-bg** [comment]
@mamarilmanson Nice! I like it this way but.... my cosin said she likes it better when the thinnest part of the K is as thin as the first time...

@mamarilmanson ~ Now you should decide if it is good enough or not... :stuck_out_tongue_winking_eye:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ I would stay with this version... when I tried thinning the part you told me it took/distorted the 3d effect I was expressing on the design... hope you would understand... :)

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ No problem... Now we need only @fry- and @alketii to say that they like the logo :smile:

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ ok... thanks... :D

**Comment by alketii** [comment]
Please ask erik, he is the artist.

**Comment by bojidar-bg** [comment]
@alketii ~ Please replay with "I like it" or "I dislike it" :stuck_out_tongue_winking_eye: 

And yeah, I forgot @erik90mx ... My bad...

**Comment by erik90mx** [comment]
I like the polish in the logo, the shape of the K is better now :) , generally I don't accept the first proposal of a logo, just after see more proposals of the same artist (to know his style and push him to make something better) but that's in the work, this is an Open Organization so the other member opinions are the point.
After all it will be the flag that Kobuge will stand for a long time :)

**Comment by bojidar-bg** [comment]
@erik90mx ~ O! That flag thing is an idea.... just imagine the flat K waving in some future 3D game we might make... (OFC, a gray version of it, not the white one...)

And when talking about a gray version.... @mamarilmanson ~ Can you make a third version, that is like the flat one, but has the gray and the white inverted (so, gray K on white background)?

**Comment by mamarilmanson** [comment]
yes sure... and actually to explain the logo... it's a combination of K and G... look at the K and G of the text... just in case you did not notice... :)

**Comment by mamarilmanson** [comment]
![kobuge_games_flag_logo](https://cloud.githubusercontent.com/assets/3820189/8584589/b93ae4b0-260a-11e5-8bca-4df79d3f41aa.jpg)

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ Ok, can you make a new repo (call it kobuge/logo), and submit all the logos, with their sources?

**Comment by mamarilmanson** [comment]
@bojidar-bg ~ can't it be on the mailing list???

**Comment by bojidar-bg** [comment]
@mamarilmanson ~ I'll create the repo.. You should just commit them. It can't be on the mailing list, because it will be hard to find it for newcomers... plus, I don't think we should keep the logo in some well-hidden mailing list :smile:

**Comment by mamarilmanson** [comment]
oh ok haha 

:+1: 

will do it later... when I get home... :D

**Comment by bojidar-bg** [comment]
@mamarilmanson  ~ https://github.com/KOBUGE-Games/logo (Add a LICENSE.md with some CC-something license, pls)

E.g. http://creativecommons.org/licenses/by-sa/4.0/ or  http://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by mamarilmanson** [comment]
Yes... thanks... :+1:

**Comment by mamarilmanson** [comment]
It would be awesome if godot also has something like that "Achieved with Cryengine" at the beginning of the video... :D

https://www.youtube.com/watch?v=e5Y_jS_2tew

**Comment by bojidar-bg** [comment]
@mamarilmanson Well, here is something I made a while ago...
![godot_logo](https://cloud.githubusercontent.com/assets/5276727/8644309/a3521634-2946-11e5-95b1-dfc24bfec6f8.png)
Just insert "Made with" above it :smile:

**Comment by mamarilmanson** [comment]
It would be better if there was a voice over... just my opinion... I'm thinking of a line the Juan Alpaca would say... XD

**Comment by bojidar-bg** [comment]
Ok, I think we should close this... (to continue the "conversation" open an issue in the other repo :smile: )
