### ISSUE TITLE
Add gun recoil

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#45]
Well right now the player just fire the gun, but it seems very robotic and plane
what it needs is a gun shake/recoil to feel the power of the gun :)
PD: Like in the real life the recoil may add some random to the bullet direction or control?

**Comment by bojidar-bg** [comment]
:+1:⁵

**Comment by erik90mx** [comment]
This commit add the recoil and variation of the bullets: https://github.com/KOBUGE-Games/ringed/commit/2378ccce42e974af1fcbcd92fce61f97c3cc5967

Now it needs the arm animation to be more real
