### ISSUE TITLE
Add shell casings particles when a bullet is shot

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#46]
Like the title said, we can add some shell casings when a bullet is fired
the shell will be in the ground a little time and then disappear.

**Comment by bojidar-bg** [comment]
@erik90mx Do you think you can manage to do this, if you have the assets?

**Comment by erik90mx** [comment]
@bojidar-bg  I have an idea to implement it, so yes.

**Comment by bojidar-bg** [comment]
Ok, then you can use some dummy gfx for now.... :wink:

**Comment by erik90mx** [comment]
it is done in this commit: https://github.com/KOBUGE-Games/ringed/commit/9fe679b0089f24dbec8a204af4a709190bc6703a
