### ISSUE TITLE
fps changes from 50 to 6 in unknown reason

### ISSUE THREAD

**Issue by zhagsenkk** [KOBUGE-Games/ringed#48]
I use the stone make a sqare to surround the enemy,and there are more than forty "enemy_kamikaze".I shoot randomly,and during a period of time,fps comes down to 7 or 6.

**Comment by erik90mx** [comment]
@bojidar-bg  maybe is something about that every bullet has a fixed process running at the time? @zhagsenkk  what are your hardware specs?

**Comment by bojidar-bg** [comment]
@erik90mx it's the bullet lights! (Will open an issue about it in a sec :) )

**Comment by erik90mx** [comment]
@bojidar-bg okidoki, well I'm working with the bullet and gun xml and scripts for the casings, I make some minor changes to them, I will try to commit them today if is possible, in order to fix this after.

**Comment by bojidar-bg** [comment]
@zhagsenkk BTW, what happens when you have like 100 spiders (kamikadze or not) on the screen at once?

**Comment by erik90mx** [comment]
@bojidar-bg  yep good point, they have lights attached too :)

**Comment by zhagsenkk** [comment]
@erik90mx GT-630m/win8.1/i5-3210m

![11](https://cloud.githubusercontent.com/assets/10054853/8958786/708cb8ee-3639-11e5-8671-404f7251d622.gif)
![22](https://cloud.githubusercontent.com/assets/10054853/8958787/709376f2-3639-11e5-867f-5b8dd69ec244.gif)
![33](https://cloud.githubusercontent.com/assets/10054853/8958788/709f1c0a-3639-11e5-993c-255115f9bce4.gif)
![44](https://cloud.githubusercontent.com/assets/10054853/8958789/70a39b4a-3639-11e5-9b5f-b520d11c7cdd.gif)

**Comment by zhagsenkk** [comment]
software named "Fraps"  to show fps.

**Comment by erik90mx** [comment]
First to all @zhagsenkk thanks for take the time to make that tests :+1: we really appreciate that, I understand better the scenario, I will try to reproduce it now.

@bojidar-bg:  I'm thinking that maybe has something to do with the colliders.

**Comment by zhagsenkk** [comment]
@erik90mx Best wishes to you! 
:)

**Comment by bojidar-bg** [comment]
@erik90mx I think that physics and collisions will have negligible impact on the FPS. Low FPS comes from the lights, I think. :smiley:
@zhagsenkk Thanks for providing those screenshots!

**Comment by erik90mx** [comment]
@zhagsenkk  just a quick thing that will be helpful to make more test (show actual FPS in the console) I will try to know how to integrate the FPS number natively in the screen. 

@bojidar-bg l will try to make the same tests than in the screenshots to know exactly what and why >:)

**Comment by zhagsenkk** [comment]
![s](https://cloud.githubusercontent.com/assets/10054853/8959622/75bfb8ca-363e-11e5-9418-274a36261ba3.gif)
Light!But the reason that fps comes down still unknown.
@erik90mx 
FPS in the console { FPS: 82FPS: 82FPS: 80FPS: 80FPS: 82FPS: 82 },it's the same as the number shown in game.
tools: http://www.fraps.com/

**Comment by bojidar-bg** [comment]
@zhagsenkk You made this screen by disabling/removing the lights from the bullet and spider scenes, right?

**Comment by bojidar-bg** [comment]
@erik90mx It's not hard to do it, just make an FPSLabel.gd that extends Label :smile:

**Comment by zhagsenkk** [comment]
@bojidar-bg just set the light disabled.Nothing is removed.

**Comment by bojidar-bg** [comment]
@zhagsenkk I was asking just to make sure no black magic is involved :wink:

**Comment by erik90mx** [comment]
@bojidar-bg  and @zhagsenkk well now FPS is in a label (for now always activated, it will be important in this debug stage): https://github.com/KOBUGE-Games/ringed/commit/2ec92531f267944ef74cecf41b34cbaf015483a4

**Comment by zhagsenkk** [comment]
I have thought this project was dead.But you are still here.![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f609.png)

**Comment by bojidar-bg** [comment]
@zhagsenkk HoooHoohoo.... KOBUGE never dies :smiling_imp: We are just sometimes somewhat busy... somehow :smiley:

**Comment by erik90mx** [comment]
@zhagsenkk well we were in this issues: https://github.com/KOBUGE-Games/ringed/issues/19 and
https://github.com/KOBUGE-Games/ringed/issues/47
they are a little time consume, but will be needed to focus the dev :)
PD: After that FPS label, now I will try to make a workaround to get lights with performance in bullets and spiders.

**Comment by erik90mx** [comment]
@zhagsenkk well after a little time, I got the cage http://prntscr.com/7yf1hc , now I will try yo make some tests.

**Comment by zhagsenkk** [comment]
Good jod,man.You can copy more spawners.
Sleep............22:41,guess where I am
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f603.png).
.

**Comment by bojidar-bg** [comment]
@zhagsenkk North/South America :smile:

**Comment by erik90mx** [comment]
@zhagsenkk probably in an Asian country :)

**Comment by ObaniGemini** [comment]
@zhagsenkk probably on Earth. But I can mistake :)

**Comment by erik90mx** [comment]
@bojidar-bg and @zhagsenkk in this commit I added a second label, this one will count every enemy that is in the scene, and submit the test map (edited the forest), right now when there are 200 kamikazes the FPS is in 5... so maybe there is other issue more than the lights.
-I try to delete the animationPlayer that scale the lights in the enemies but the problem persisted.
-I try to drop some animation frames in the spiders (and just have 3), but the same
-I delete the lights in the enemy scene, and the problem persist (I can't have more than 200, because FPS was afected)
-The last thing that I try was all the mention tests in one, but same problem.

@bojidar-bg maybe we need to refactor the enemy classes?

https://github.com/KOBUGE-Games/ringed/commit/9b27da728f85cee86131aec1c40a9b9a31481dd4

**Comment by bojidar-bg** [comment]
@erik90mx maybe you can disable the fixed_process ?

**Comment by erik90mx** [comment]
@bojidar-bg  where do you mean? and what will be the consecuences?

**Comment by bojidar-bg** [comment]
@erik90mx are you sure you want to at-mention https://github.com/where ?

**Comment by erik90mx** [comment]
edited :)

**Comment by bojidar-bg** [comment]
@erik90mx I was thinking to remove the logic in the spider script, so we can check if it is dropping the framerate.

**Comment by zhagsenkk** [comment]
Maybe there would not exist so much kamikazes when you play.You can limit the number of enemy on screen at one time.

**Comment by bojidar-bg** [comment]
@zhagsenkk ~ Well, yeah, it is quite strange(and unfortunate) if they get to 200 enemies on-screen.

@erik90mx Quick question. does your FPS go up when you go away from the spiders? E.g. when you have 200 spiders, but they are off-screen?

**Comment by erik90mx** [comment]
@bojidar-bg  I try that, but is the same, even when I disable the sprite (so its a process problem)

**Comment by bojidar-bg** [comment]
@erik90mx (an image is worth a thousand words...)
![screenshot](https://cloud.githubusercontent.com/assets/5276727/9026002/c74256a4-3926-11e5-8b35-6fff2880ca34.png).

This is with visibilityEnabler, so the spiders aren't fixed_processed while out-of-screen. Only when I go near them my FPS goes down to 5, but that's another story :smile:. I'll commit it soon.

**Comment by erik90mx** [comment]
@bojidar-bg this way the enemy will not move until we reach them?, do you think it will affect the gameplay some how?

I will read the commit for sure :) it is interesting the use of it.

**Comment by bojidar-bg** [comment]
@erik90mx No, I don't think this will be a problem, because it will be unrealistic for the spider to see the player when the player can't see it (unfair advantage). Also, we thought to make spiders target only players in some distance, not all players. :smiley: 

BTW, for the record, the commit this was added is 41e1498dbca9171fe4040aa0dbb0fdca348ea9a6

**Comment by erik90mx** [comment]
@bojidar-bg so it was a Godot UI option? :)

**Comment by bojidar-bg** [comment]
@erik90mx E.g.?

**Comment by erik90mx** [comment]
@bojidar-bg I I refer to that, because just saw .xml files in that commit :)    http://s23.postimg.org/ow5v6dpcr/screenshot_337.png

**Comment by bojidar-bg** [comment]
@erik90mx No, there is just some build-in node called VisibilityEnabler2D. :smile_cat:

**Comment by erik90mx** [comment]
@bojidar-bg got it, I need to test it in my computer :)

**Comment by erik90mx** [comment]
@bojidar-bg well the problem is solved when the player is not seeing the enemies, do you think it will be necessary to lock the enemy quantity?

**Comment by bojidar-bg** [comment]
@erik90mx no, now only the other issue (the one about the effects #49) is left
