### ISSUE TITLE
Add an option to disable some effects

### ISSUE THREAD

**Issue by bojidar-bg** [KOBUGE-Games/ringed#49]
Some effect (bullet lights in particular #48 ) are quite hard to compute. We should add a settings menu, so users with slower computers (hehe, includes me) can play the game at 60 FPS flat.

(Note: to remove bullet lights, you can either remove the node or use set_disabled(true)).

**Comment by erik90mx** [comment]
@bojidar-bg  set_disabled() will do the work, in case the person want to enable them in run time :)
is there a way to fake them? or reduce its performance consume.

**Comment by bojidar-bg** [comment]
@erik90mx Maybe we can disable the light by default, and enable it in `bullet.gd::_ready()`. 

The other option I see is to make another scene called `bullet_nolights.xml` and switch between them in the player script, but I see this option as being more troublesome (because we will have to update both of them). Alternatively, we can have `bullet_nolights.xml` instanced in `bullet.xml` :smile: 

I hope those options are enough.

**Comment by erik90mx** [comment]
@bojidar-bg  I think I finish this issue: https://github.com/KOBUGE-Games/ringed/issues/46
I will try to handle this one now, and then I will go for this one later: https://github.com/KOBUGE-Games/ringed/issues/43

I'm thinking in experiment with a sprite with emit material to try to fake the light... maybe or just to make the bullets visible at night

**Comment by ObaniGemini** [comment]
I think my computer is worse than yours @bojidar-bg :D

**Comment by bojidar-bg** [comment]
@erik90mx should I try to do it, or you think you can find the time?

**Comment by erik90mx** [comment]
@bojidar-bg please help me with this one :) , I was thinking in not disable the lights, just change them to a sprite with emit material and same animations.

**Comment by bojidar-bg** [comment]
@erik90mx Well, Light2D nodes won't exist if additive sprites looked the same :smile:... I might try to do it tonight (or Saturday), though....

(Just thinking about it... We can make three options, Light2D, Sprite or none. That way we might leave the user do the hard decision :smiley: )

**Comment by erik90mx** [comment]
@bojidar-bg  I like the idea :+1:

**Comment by bojidar-bg** [comment]
@erik90mx Hmmm..Hummmm! :smile:

**Comment by bojidar-bg** [comment]
Almost there!
