### ISSUE TITLE
Spider animation different times

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#5]
Well each time I die I'm round by spiders, and it looks amazing but
it will feel more organic movements if the spiders have different animation times, because if you look close you can see all the spiders repeat the loop at the same time.

Greetings

http://s1.postimg.org/6tlpfuer3/screenshot_66.png

**Comment by bojidar-bg** [comment]
That will be fixed when we have animation based on bones, etc. (ask @fry- for more info..)
