### ISSUE TITLE
Some minor code changes and then can't open some scenes

### ISSUE THREAD

**Issue by cjhorton** [KOBUGE-Games/ringed#50]
Running Godot v 1.1 stable

Inside setup_game_graphics.gd:
    #checkbox = get_node("Option1/CheckBox") - caused error
    checkbox = get_node("Options/Option1/On")

Inside menu_animation.gd, there were several of these:
# animations.stop(true) - caused error

animations.stop()

And then, I couldn't open bombs.xml, even in the editor.  Couldn't open a few other scenes either.

**Comment by erik90mx** [comment]
@cjhorton well some minutes ago there were a conflict in the main.xml so we need to solve that, do you check with an actual Godot build? in the facebook page there are several users posting nice builds :)
@bojidar-bg I think we should to manage the main menu .xml with instantiate scenes for the different menus (to avoid more conflicts in the menu), can you please check this issue? I'm in the middle of a travel

**Comment by bojidar-bg** [comment]
@cjhorton make note that we develop on dev version.
@erik90mx Good idea. BTW, you fixed all of the merge errors, right?

**Comment by erik90mx** [comment]
@bojidar-bg for the main.xml file, yes, but there is an error with the global script, can you check it?

**Comment by bojidar-bg** [comment]
@erik90mx What is the error message? (I have committed some half-baked changes...)

**Comment by erik90mx** [comment]
I save this screenshot of the error: http://s23.postimg.org/6fp8ksdjv/screenshot_370.png

**Comment by cjhorton** [comment]
@bojidar-bg Updated and works now after the edit in the screenshot.

**Comment by erik90mx** [comment]
@cjhorton  nice to hear that :) and thank you very much for the notification.
