### ISSUE TITLE
Another out of topic...

### ISSUE THREAD

**Issue by mamarilmanson** [KOBUGE-Games/ringed#51]
Me and a fellow Godot user has been talking about rewriting godot's ui and clean the codebase(he's the dev)... and maybe work on rebranding it... anyone wants to join??? or those who you know who are C++ devs that may want to join... please do... I'm on a recruitment phase now... :)

**Comment by bojidar-bg** [comment]
@mamarilmanson Repost in godot forums?

**Comment by mamarilmanson** [comment]
uhm... if possible were doing it underground... :)

**Comment by mamarilmanson** [comment]
any reason why our irc is a deserted place? :(

there are some that likes to join us... it's sad no one can welcome them...

**Comment by erik90mx** [comment]
@mamarilmanson right now i'm on a travel, next week i will work like always :)

**Comment by mamarilmanson** [comment]
:+1:
