### ISSUE TITLE
License not done

### ISSUE THREAD

**Issue by bojidar-bg** [KOBUGE-Games/ringed#54]
There are some `{values}` in the license file

**Comment by ivanskodje** [comment]
How would this work when there are more than one contributor? Is there one "main" contributor; whose name is great and should be put there? I am guessing it would be whomever started this project :)

**Comment by akien-mga** [comment]
The `{values}` in the license file should not be modified, it's the technical explication on how to apply the GPL to a project. What we need is to put the short license text in the README and/or the .gd headers, like e.g. [in Minilens](https://github.com/KOBUGE-Games/minilens#license).

Though we're missing the copyright line in Minilens, see https://github.com/KOBUGE-Games/minilens/blob/master/LICENSE.txt#L634-L635

Copyright should be attributed to KOBUGE Games.

**Comment by akien-mga** [comment]
Added the copyright to Minilens and Kumquat too. Some other projects might have to be fixed too.

**Comment by ivanskodje** [comment]
:+1:
