### ISSUE TITLE
stepsSounds are fade off

### ISSUE THREAD

**Issue by erik90mx** [KOBUGE-Games/ringed#8]
When the player moves the sound will play but if the player stop the sound needs to end at the same time.

**Comment by erik90mx** [comment]
I think is fixed with this commit https://github.com/KOBUGE-Games/ringed/commit/44beb0450006a2b30868d7ec7511b24ff1f464e2

**Comment by bojidar-bg** [comment]
@erik90mx can you test to see if it is already fixed? (I'll test tonight if you haven't already closed it)
